name: 'Login to Docker Hub'
description: 'Read Docker Hub credentials from Vault and log in to the registry'

inputs:
  docker-registry:
    description: 'Docker registry hostname'
    required: false
    default: 'ghcr.io'
  docker-io-username:
    description: 'Username for Docker Hub login'
    required: false
    default: ''
  docker-io-password:
    description: 'Password/token for Docker Hub login'
    required: false
    default: ''
outputs:
  registry:
    value: ${{ steps.generate.outputs.registry }}
    description: 'Docker Hub registry hostname'
  repository:
    value: ${{ steps.generate.outputs.repository }}
    description: 'Docker Hub repository or organization'

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-io-username }}
        password: ${{ inputs.docker-io-password }}

    - name: Expose registry destination
      id: generate
      shell: bash
      run: |
        echo "registry=${{ inputs.docker-registry }}" >> "$GITHUB_OUTPUT"
        echo "repository=${{ github.repository }}" >> "$GITHUB_OUTPUT"
